version: '3.8'

services:
  app:
    build: .
    container_name: go-todo-app
    ports:
      - "9090:9090"
    depends_on:
      - db
    env_file:
      - .env
    command: ["/wait-for.sh", "db", "./go-todo"]
    environment:
      DB_HOST: ${DB_HOST}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_PORT: ${DB_PORT}
      DB_SSLMODE: ${DB_SSLMODE}
      # - DB_URL=${DB_URL}
    restart: always

  db:
    image: postgres:15-alpine
    container_name: go-todo-db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
